# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-06 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_student',
            field=models.NullBooleanField(),
        ),
    ]
